### ISSUE TITLE
API endpoint for GET /users/info/ with only API key

### ISSUE THREAD

**Issue by sman591** [bencentra/WebDrink-2.0#55]
Currently, the API requires a UID, iButton, or for the current user to be logged in to CSH to get a user's info.

I think if the request provides an API key, it should not require either of those. Example:

https://webdrink.csh.rit.edu/api/index.php?request=users/info/&api_key=myApiKey

**Comment by bencentra** [comment]
I believe it does work with just the API key. Try it with your API key, it just worked for me.

It definitely isn't documented though, so I'll fix that soon!

**Comment by sman591** [comment]
Looks like it does! Sorry about that, I must've typed my API key wrong when I tried last night.
